// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KiQ24yv0SQN2VFHVAeimMdrm0kPdkjY',
    appId: '1:238254514845:web:19e63def269ee8f26f2a74',
    messagingSenderId: '238254514845',
    projectId: 'test-login2-642e2',
    authDomain: 'test-login2-642e2.firebaseapp.com',
    storageBucket: 'test-login2-642e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OM914_Bzs6A1SpNs7OFWKV4cpRFHepU',
    appId: '1:238254514845:android:f7dcd129e248bffa6f2a74',
    messagingSenderId: '238254514845',
    projectId: 'test-login2-642e2',
    storageBucket: 'test-login2-642e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Yj0V5kmPj2ajaDxLJ5a8nnFp4w_ggms',
    appId: '1:238254514845:ios:c63783aa8992a1ae6f2a74',
    messagingSenderId: '238254514845',
    projectId: 'test-login2-642e2',
    storageBucket: 'test-login2-642e2.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Yj0V5kmPj2ajaDxLJ5a8nnFp4w_ggms',
    appId: '1:238254514845:ios:c63783aa8992a1ae6f2a74',
    messagingSenderId: '238254514845',
    projectId: 'test-login2-642e2',
    storageBucket: 'test-login2-642e2.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3KiQ24yv0SQN2VFHVAeimMdrm0kPdkjY',
    appId: '1:238254514845:web:0466a7d313d92fdc6f2a74',
    messagingSenderId: '238254514845',
    projectId: 'test-login2-642e2',
    authDomain: 'test-login2-642e2.firebaseapp.com',
    storageBucket: 'test-login2-642e2.firebasestorage.app',
  );
}
